# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QGroupBox, QLabel, QLineEdit, QPushButton,
    QScrollArea, QSizePolicy, QTextEdit, QWidget)

class Ui_main_ui(object):
    def setupUi(self, main_ui):
        if not main_ui.objectName():
            main_ui.setObjectName(u"main_ui")
        main_ui.resize(480, 600)
        main_ui.setMinimumSize(QSize(480, 600))
        main_ui.setMaximumSize(QSize(480, 600))
        self.main_widget = QWidget(main_ui)
        self.main_widget.setObjectName(u"main_widget")
        self.main_widget.setGeometry(QRect(0, 0, 480, 600))
        self.main_widget.setStyleSheet(u"")
        self.group_main = QGroupBox(self.main_widget)
        self.group_main.setObjectName(u"group_main")
        self.group_main.setGeometry(QRect(0, 0, 481, 601))
        self.group_main.setStyleSheet(u"")
        self.scroll_status = QScrollArea(self.group_main)
        self.scroll_status.setObjectName(u"scroll_status")
        self.scroll_status.setGeometry(QRect(10, 140, 461, 451))
        self.scroll_status.setWidgetResizable(True)
        self.scroll_contents_status = QWidget()
        self.scroll_contents_status.setObjectName(u"scroll_contents_status")
        self.scroll_contents_status.setGeometry(QRect(0, 0, 459, 449))
        self.textarea_status = QTextEdit(self.scroll_contents_status)
        self.textarea_status.setObjectName(u"textarea_status")
        self.textarea_status.setGeometry(QRect(0, 0, 461, 451))
        self.scroll_status.setWidget(self.scroll_contents_status)
        self.button_check = QPushButton(self.group_main)
        self.button_check.setObjectName(u"button_check")
        self.button_check.setGeometry(QRect(10, 90, 71, 30))
        self.button_check.setStyleSheet(u"")
        self.label_port = QLabel(self.group_main)
        self.label_port.setObjectName(u"label_port")
        self.label_port.setGeometry(QRect(10, 10, 221, 31))
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_port.setFont(font)
        self.button_close = QPushButton(self.group_main)
        self.button_close.setObjectName(u"button_close")
        self.button_close.setGeometry(QRect(170, 90, 71, 30))
        self.button_close.setStyleSheet(u"")
        self.button_open = QPushButton(self.group_main)
        self.button_open.setObjectName(u"button_open")
        self.button_open.setGeometry(QRect(90, 90, 71, 30))
        self.button_open.setStyleSheet(u"")
        self.combo_ports = QComboBox(self.group_main)
        self.combo_ports.setObjectName(u"combo_ports")
        self.combo_ports.setGeometry(QRect(10, 50, 231, 31))
        self.hline_1 = QFrame(self.group_main)
        self.hline_1.setObjectName(u"hline_1")
        self.hline_1.setGeometry(QRect(250, 20, 3, 100))
        self.hline_1.setFrameShape(QFrame.Shape.VLine)
        self.hline_1.setFrameShadow(QFrame.Shadow.Sunken)
        self.input_hotkey_start = QLineEdit(self.group_main)
        self.input_hotkey_start.setObjectName(u"input_hotkey_start")
        self.input_hotkey_start.setGeometry(QRect(360, 50, 81, 30))
        self.label_actions = QLabel(self.group_main)
        self.label_actions.setObjectName(u"label_actions")
        self.label_actions.setGeometry(QRect(260, 10, 81, 31))
        self.label_actions.setFont(font)
        self.button_start = QPushButton(self.group_main)
        self.button_start.setObjectName(u"button_start")
        self.button_start.setGeometry(QRect(260, 50, 81, 30))
        self.button_start.setStyleSheet(u"")
        self.button_stop = QPushButton(self.group_main)
        self.button_stop.setObjectName(u"button_stop")
        self.button_stop.setGeometry(QRect(260, 90, 81, 30))
        self.button_stop.setStyleSheet(u"")
        self.hline_2 = QFrame(self.group_main)
        self.hline_2.setObjectName(u"hline_2")
        self.hline_2.setGeometry(QRect(350, 20, 3, 100))
        self.hline_2.setFrameShape(QFrame.Shape.VLine)
        self.hline_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_hotkeys = QLabel(self.group_main)
        self.label_hotkeys.setObjectName(u"label_hotkeys")
        self.label_hotkeys.setGeometry(QRect(360, 10, 111, 31))
        self.label_hotkeys.setFont(font)
        self.input_hotkey_stop = QLineEdit(self.group_main)
        self.input_hotkey_stop.setObjectName(u"input_hotkey_stop")
        self.input_hotkey_stop.setGeometry(QRect(360, 90, 81, 30))
        self.button_hotkey_start_ok = QPushButton(self.group_main)
        self.button_hotkey_start_ok.setObjectName(u"button_hotkey_start_ok")
        self.button_hotkey_start_ok.setGeometry(QRect(440, 50, 31, 30))
        self.button_hotkey_start_ok.setStyleSheet(u"")
        self.button_hotkey_stop_ok = QPushButton(self.group_main)
        self.button_hotkey_stop_ok.setObjectName(u"button_hotkey_stop_ok")
        self.button_hotkey_stop_ok.setGeometry(QRect(440, 90, 31, 30))
        self.button_hotkey_stop_ok.setStyleSheet(u"")
        self.vline_1 = QFrame(self.group_main)
        self.vline_1.setObjectName(u"vline_1")
        self.vline_1.setGeometry(QRect(10, 130, 460, 3))
        self.vline_1.setFrameShape(QFrame.Shape.HLine)
        self.vline_1.setFrameShadow(QFrame.Shadow.Sunken)
        QWidget.setTabOrder(self.combo_ports, self.button_check)
        QWidget.setTabOrder(self.button_check, self.button_open)
        QWidget.setTabOrder(self.button_open, self.button_close)
        QWidget.setTabOrder(self.button_close, self.button_start)
        QWidget.setTabOrder(self.button_start, self.button_stop)
        QWidget.setTabOrder(self.button_stop, self.input_hotkey_start)
        QWidget.setTabOrder(self.input_hotkey_start, self.button_hotkey_start_ok)
        QWidget.setTabOrder(self.button_hotkey_start_ok, self.input_hotkey_stop)
        QWidget.setTabOrder(self.input_hotkey_stop, self.button_hotkey_stop_ok)
        QWidget.setTabOrder(self.button_hotkey_stop_ok, self.scroll_status)
        QWidget.setTabOrder(self.scroll_status, self.textarea_status)

        self.retranslateUi(main_ui)

        QMetaObject.connectSlotsByName(main_ui)
    # setupUi

    def retranslateUi(self, main_ui):
        main_ui.setWindowTitle(QCoreApplication.translate("main_ui", u"Serial Input Monitor", None))
        main_ui.setProperty(u"theme", "")
        self.main_widget.setProperty(u"theme", "")
        self.group_main.setTitle("")
#if QT_CONFIG(tooltip)
        self.button_check.setToolTip(QCoreApplication.translate("main_ui", u"Check selected COM port", None))
#endif // QT_CONFIG(tooltip)
        self.button_check.setText(QCoreApplication.translate("main_ui", u"Check", None))
        self.label_port.setText(QCoreApplication.translate("main_ui", u"Serial Port", None))
#if QT_CONFIG(tooltip)
        self.button_close.setToolTip(QCoreApplication.translate("main_ui", u"Close selected COM port", None))
#endif // QT_CONFIG(tooltip)
        self.button_close.setText(QCoreApplication.translate("main_ui", u"Close", None))
#if QT_CONFIG(tooltip)
        self.button_open.setToolTip(QCoreApplication.translate("main_ui", u"Open selected COM port", None))
#endif // QT_CONFIG(tooltip)
        self.button_open.setText(QCoreApplication.translate("main_ui", u"Open", None))
#if QT_CONFIG(tooltip)
        self.combo_ports.setToolTip(QCoreApplication.translate("main_ui", u"COM Ports", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.input_hotkey_start.setToolTip(QCoreApplication.translate("main_ui", u"Start Hotkey", None))
#endif // QT_CONFIG(tooltip)
        self.label_actions.setText(QCoreApplication.translate("main_ui", u"Actions", None))
#if QT_CONFIG(tooltip)
        self.button_start.setToolTip(QCoreApplication.translate("main_ui", u"Start Listening", None))
#endif // QT_CONFIG(tooltip)
        self.button_start.setText(QCoreApplication.translate("main_ui", u"Start", None))
#if QT_CONFIG(shortcut)
        self.button_start.setShortcut(QCoreApplication.translate("main_ui", u"F9", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.button_stop.setToolTip(QCoreApplication.translate("main_ui", u"Stop Listening", None))
#endif // QT_CONFIG(tooltip)
        self.button_stop.setText(QCoreApplication.translate("main_ui", u"Stop", None))
#if QT_CONFIG(shortcut)
        self.button_stop.setShortcut(QCoreApplication.translate("main_ui", u"F10", None))
#endif // QT_CONFIG(shortcut)
        self.label_hotkeys.setText(QCoreApplication.translate("main_ui", u"Hotkeys", None))
#if QT_CONFIG(tooltip)
        self.input_hotkey_stop.setToolTip(QCoreApplication.translate("main_ui", u"Stop Hotkey", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.button_hotkey_start_ok.setToolTip(QCoreApplication.translate("main_ui", u"Save Hotkey", None))
#endif // QT_CONFIG(tooltip)
        self.button_hotkey_start_ok.setText(QCoreApplication.translate("main_ui", u"Ok", None))
#if QT_CONFIG(tooltip)
        self.button_hotkey_stop_ok.setToolTip(QCoreApplication.translate("main_ui", u"Save Hotkey", None))
#endif // QT_CONFIG(tooltip)
        self.button_hotkey_stop_ok.setText(QCoreApplication.translate("main_ui", u"Ok", None))
    # retranslateUi

